version: '2'
services:
 neuralnet:
   build: .
   image: neuralnet
   container_name: "neuralnet"
   # working_dir: "/etc/nginx"
   # volumes:
     # - ./conf/default:/etc/nginx/sites-available/default
     # - ./conf/nginx.conf:/etc/nginx/nginx.conf
